---
kind: pipeline
name: compliance
type: docker

steps:
    -   name: install
        image: thecodingmachine/php:8.2-v4-cli
        pull: always
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            PHP_EXTENSION_GD: 1
            PHP_EXTENSION_IMAGICK: 1
        commands:
            - composer validate --ansi --no-check-all --no-check-publish
            - sudo composer install --no-progress --ansi --prefer-dist
    -   name: phplint
        image: thecodingmachine/php:8.2-v4-cli
        environment:
            PHP_EXTENSION_GD: 1
            PHP_EXTENSION_IMAGICK: 1
            PHP_INI_ERROR_REPORTING: E_ALL & ~(E_STRICT | E_NOTICE | E_WARNING | E_DEPRECATED)
        commands:
            - composer phplint
        depends_on: [ install ]
    -   name: phpcs
        image: thecodingmachine/php:8.2-v4-cli
        environment:
            PHP_EXTENSION_GD: 1
            PHP_EXTENSION_IMAGICK: 1
            PHP_INI_ERROR_REPORTING: E_ALL & ~(E_STRICT | E_NOTICE | E_WARNING | E_DEPRECATED)
        commands:
            - composer phpcs
        depends_on: [ install ]
    -   name: phpstan
        image: thecodingmachine/php:8.2-v4-cli
        environment:
            PHP_EXTENSION_GD: 1
            PHP_EXTENSION_IMAGICK: 1
        commands:
            - composer phpstan
        depends_on: [ install ]

trigger:
    ref:
        - refs/heads/master
        - refs/pull/**
        - refs/tags/**
---
kind: pipeline
name: tests
type: docker

steps:
    -   name: install
        image: thecodingmachine/php:8.2-v4-cli
        pull: always
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            PHP_EXTENSION_GD: 1
            PHP_EXTENSION_IMAGICK: 1
        commands:
            - composer validate --ansi --no-check-all --no-check-publish
            - sudo composer install --no-progress --ansi --prefer-dist
    -   name: phpunit
        image: thecodingmachine/php:8.2-v4-cli
        environment:
            PHP_EXTENSION_GD: 1
            PHP_EXTENSION_IMAGICK: 1
        commands:
            - composer phpunit

trigger:
    ref:
        - refs/heads/master
        - refs/pull/**
        - refs/tags/**