---
kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            restore: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_default'
            archive_format: gzip
            mount:
                - ./vendor
        depends_on: [ clone ]
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer self-update
            - composer --version
            - php -v
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist
        depends_on: [ restore-cache ]
    -   name: phplint
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phplint
        depends_on: [ install ]
    -   name: phpstan
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phpstan
        depends_on: [ install ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            rebuild: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_default'
            archive_format: gzip
            mount:
                - ./vendor
        volumes:
            -   name: drone-cache
                path: /tmp/cache
        depends_on: [ install ]

trigger:
    branch:
        - master
        - drone
    event:
        exclude:
            - cron

---
kind: pipeline
name: outdated
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            restore: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_outdated'
            archive_format: gzip
            mount:
                - ./vendor
        depends_on: [ clone ]
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer self-update
            - composer --version
            - php -v
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist --no-dev
        depends_on: [ restore-cache ]
    -   name: outdated
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer outdated -n --direct --strict --ansi --ignore roave/security-advisories --ignore robmorgan/phinx
        depends_on: [ install ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            rebuild: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_outdated'
            archive_format: gzip
            mount:
                - ./vendor
        depends_on: [ install ]

trigger:
    branch:
        - master
        - drone

---
kind: signature
hmac: 34caa46db162b0f26b55f9eae2fa38c86e20a3710ed42bf6c939ce1eaacc8114

...
