---
kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        settings:
            backend: "filesystem"
            restore: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_default'
            archive_format: "gzip"
            mount:
                - 'vendor'
        volumes:
            -   name: drone-cache
                path: /tmp/cache
        depends_on: [ clone ]
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer self-update
            - composer --version
            - php -v
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist
        depends_on: [ restore-cache ]
    -   name: phplint
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phplint
        depends_on: [ install ]
    -   name: phpstan
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phpstan
        depends_on: [ install ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        settings:
            backend: "filesystem"
            rebuild: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_default'
            archive_format: "gzip"
            mount:
                - 'vendor'
        volumes:
            -   name: drone-cache
                path: /tmp/cache
        depends_on: [ install ]

trigger:
    branch:
        - master
        - drone
    event:
        exclude:
            - cron

volumes:
    -   name: drone-cache
        host:
            path: /var/lib/cache

---
kind: pipeline
name: outdated
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        settings:
            backend: "filesystem"
            restore: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_outdated'
            archive_format: "gzip"
            mount:
                - 'vendor'
        volumes:
            -   name: drone-cache
                path: /tmp/cache
        depends_on: [ clone ]
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer self-update
            - composer --version
            - php -v
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist --no-dev
        depends_on: [ restore-cache ]
    -   name: outdated
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer outdated -n --direct --strict --ansi --ignore roave/security-advisories --ignore robmorgan/phinx
        depends_on: [ install ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        settings:
            backend: "filesystem"
            rebuild: true
            cache_key: '{{ checksum "composer.json" }}_{{ checksum "composer.lock" }}_outdated'
            archive_format: "gzip"
            mount:
                - 'vendor'
        volumes:
            -   name: drone-cache
                path: /tmp/cache
        depends_on: [ install ]

trigger:
    branch:
        - master
        - drone

volumes:
    -   name: drone-cache
        host:
            path: /var/lib/cache
---
kind: signature
hmac: f9241d7b4b61b0d2f98cf2e9c3ce4608dfee78151fc5a9729ea60859e05889b4

...
