kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: php:7.3
        commands:
            - DEBIAN_FRONTEND=noninteractive apt-get -qq update && apt-get -qq install git unzip --no-install-recommends > /dev/null
            - curl -sS https://getcomposer.org/installer | php --
            - ./composer.phar global require hirak/prestissimo --no-progress --ansi --no-suggest --prefer-dist
            - ./composer.phar install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist
    -   name: phplint
        image: php:7.3
        commands:
            - ./composer.phar phplint
        depends_on: [ install ]
    -   name: phpstan
        image: php:7.3
        commands:
            - docker-php-ext-install pdo_mysql > /dev/null # https://github.com/phpstan/phpstan/issues/2883
            - ./composer.phar phpstan
        depends_on: [ phplint ]

trigger:
    branch:
        - master
        - drone
    event:
        exclude:
            - cron

---
kind: pipeline
name: outdated
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: composer
        commands:
            - composer global require hirak/prestissimo --no-progress --ansi --no-suggest --prefer-dist
            - composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist --no-dev
    -   name: outdated
        image: composer
        commands:
            - composer outdated -n --direct --strict --ansi --ignore roave/security-advisories
trigger:
    branch:
        - master
