kind: pipeline
name: compliance
type: docker

steps:
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer validate --ansi --no-check-all --no-check-publish
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist
    -   name: phplint
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phplint
        depends_on: [ install ]
    -   name: phpcs
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phpcs
        depends_on: [ install ]
    -   name: phpstan
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phpstan
        depends_on: [ install ]

trigger:
    event:
        exclude:
            - promote

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer validate --ansi --no-check-all --no-check-publish
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist
    -   name: phpspec
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phpspec

trigger:
    event:
        exclude:
            - promote

---
kind: pipeline
name: artifacts
type: docker

steps:
    -   name: collect
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer validate --ansi --no-check-all --no-check-publish
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist --no-dev
    -   name: upload
        image: plugins/s3-cache
        settings:
            rebuild: true
            path: artifacts/${DRONE_REPO_NAME}/${DRONE_COMMIT}/
            mount:
                - vendor
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
        when:
            target:
                - production
    -   name: flush
        image: plugins/s3-cache
        settings:
            flush: true
            flush_age: 14
            flush_path: artifacts/${DRONE_REPO_NAME}/
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
        when:
            target:
                - production

trigger:
    event:
        - promote
