kind: pipeline
name: default
type: docker

steps:
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer self-update
            - composer --version
            - php -v
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist
        depends_on: [ clone ]
    -   name: phplint
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phplint
        depends_on: [ install ]
    -   name: phpstan
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer phpstan
        depends_on: [ install ]

---
kind: pipeline
name: outdated
type: docker

steps:
    -   name: install
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer self-update
            - composer --version
            - php -v
            - sudo composer install --no-progress --ansi --no-suggest --ignore-platform-reqs --prefer-dist --no-dev
    -   name: outdated
        image: thecodingmachine/php:7.3-v3-cli
        commands:
            - composer outdated -n --direct --strict --ansi --ignore roave/security-advisories --ignore robmorgan/phinx
