openapi: 3.0.3
info:
    title: Mei Image Server
    version: 1.0.0
servers:
    -   url: 'https://mei.animebytes.local:7443'
        description: Vagrant
paths:
    /upload/user:
        post:
            summary: Upload one or more images from files
            tags:
                - upload
            security:
                - EncryptedTokenContent: []
                  EncryptedTokenSignature: []
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                image[]:
                                    type: array
                                    description: Image to upload
                                    items:
                                        type: string
                                        format: binary
                            required:
                                - image[]
            responses:
                '201':
                    description: OK
                    content:
                        application/json:
                            schema:
                                properties:
                                    success:
                                        type: boolean
                                        description: Whether action was succesful
                                    callback:
                                        type: object
                                        description: Object containing encrypted response
                                        properties:
                                            content:
                                                type: string
                                                description: Base64-encoded encrypted response
                                            sign:
                                                type: string
                                                description: HMAC signature
                                        required:
                                            - content
                                            - sign
                                    warnings:
                                        type: array
                                        description: List of warnings encountered
                                        items:
                                            type: string
                                required:
                                    - success
                                    - callback
                '400':
                    description: Empty request or unacceptable MIME restriction
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
                '403':
                    description: Invalid or expired token
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
                '415':
                    description: No Images Processed
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
    /upload/api:
        post:
            summary: Upload one or more images from URLs
            tags:
                - upload
            security:
                - SimpleHmacSignature: []
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                urls:
                                    type: array
                                    description: List of URLs pointing to images for upload
                                    items:
                                        type: string
                            required:
                                - urls
                    application/x-www-form-urlencoded:
                        encoding:
                            urls[]:
                                style: form
                                explode: true
                        schema:
                            type: object
                            properties:
                                urls[]:
                                    type: array
                                    description: List of URLs pointing to images for upload
                                    items:
                                        type: string
                            required:
                                - urls[]
            responses:
                '201':
                    description: OK
                    content:
                        application/json:
                            schema:
                                properties:
                                    success:
                                        type: boolean
                                        description: Whether action was succesful
                                    images:
                                        type: array
                                        description: List of uploaded images
                                        items:
                                            type: string
                                    warnings:
                                        type: array
                                        description: List of warnings encountered
                                        items:
                                            type: string
                                required:
                                    - success
                                    - images
                '400':
                    description: Empty request (no images supplied)
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
                '403':
                    description: Invalid API authentication
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
                '415':
                    description: No Images Processed
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
    /delete:
        post:
            summary: Delete one or more images
            tags:
                - delete
            security:
                - SimpleHmacSignature: []
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            description: List of images to remove
                            properties:
                                images:
                                    type: array
                                    items:
                                        type: string
                            required:
                                - images
                    application/x-www-form-urlencoded:
                        encoding:
                            images[]:
                                style: form
                                explode: true
                        schema:
                            type: object
                            properties:
                                images[]:
                                    type: array
                                    description: List of images to remove
                                    items:
                                        type: string
                            required:
                                - images[]
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
                '400':
                    description: No images to delete given
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
                '403':
                    description: Invalid API authentication
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HttpResponse'
components:
    schemas:
        HttpResponse:
            title: HttpResponse
            type: object
            properties:
                success:
                    type: boolean
                    description: Whether action was succesful
                warnings:
                    type: array
                    items:
                        type: string
                    description: List of warnings encountered
                error:
                    type: string
                    description: Message describing error cause
            required:
                - success
        EncryptedToken:
            title: EncryptedToken
            type: object
            properties:
                mime:
                    type: string
                    description: Specific MIME-type from allowable range to restrict newly uploaded images
                tvalid:
                    type: integer
                    description: Unix time this token is valid until
            additionalProperties: true
            required:
                - tvalid
    securitySchemes:
        SimpleHmacSignature:
            type: apiKey
            in: header
            name: X-Hmac-Signature
        EncryptedTokenContent:
            type: apiKey
            in: query
            name: t
        EncryptedTokenSignature:
            type: apiKey
            in: query
            name: s
