paths:
    migrations: '%%PHINX_CONFIG_DIR%%/migrations'

environments:
    default_migration_table: phinxlog
    default_database: development
    development:
        adapter: mysql
        host: localhost
        name: mei
        user: mei
        pass: 'mei'
        port: 3306
        charset: utf8
