name: audit

on:
    pull_request:
        branches:
            - master
        paths:
            - composer.lock
        types: [ opened, synchronize, reopened ]

concurrency:
    group: ${{ forge.workflow }}-${{ forge.ref }}
    cancel-in-progress: true

env:
    PHP_VERSION: 8.4

jobs:
    composer:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            -   name: Set up PHP
                uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    tools: composer
                    coverage: none
                env:
                    fail-fast: true
            -   name: Install dependencies
                env:
                    COMPOSER_IGNORE_PLATFORM_REQS: ext-*, lib-*
                    COMPOSER_SKIP_SCRIPTS: post-install-cmd
                run: |
                    composer validate --ansi --no-check-all --no-check-publish
                    composer install --no-progress --ansi --prefer-dist
            -   name: Audit dependencies
                run: composer audit --ansi