name: testing

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        types: [ opened, synchronize, reopened ]

env:
    PHP_VERSION: 8.4
    PHP_EXTENSIONS: xml, gd, imagick, curl, mysql, bcmath, mbstring

jobs:
    backend:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Prepare environment
                id: ext-cache
                uses: shivammathur/cache-extensions@4595bea7d6630821b0a3a4894f816402faaf324c # v1
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    key: cache-v1
            -   name: Cache extensions
                uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
                with:
                    path: ${{ steps.ext-cache.outputs.dir }}
                    key: ${{ steps.ext-cache.outputs.key }}
                    restore-keys: ${{ steps.ext-cache.outputs.key }}
            -   name: Set up PHP
                uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    tools: composer
                    coverage: none
                env:
                    fail-fast: true
            -   name: Get composer cache directory
                id: deps-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   name: Cache dependencies
                uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
                with:
                    path: ${{ steps.deps-cache.outputs.dir }}
                    key: ${{ runner.os }}-${{ runner.arch }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-${{ runner.arch }}-composer-
            -   name: Install dependencies
                run: composer install --no-progress --ansi --prefer-dist
            -   name: PHPUnit
                run: composer phpunit
    e2e:
        runs-on: ubuntu-24.04
        services:
            mariadb:
                image: mariadb:11.4
                env:
                    MYSQL_RANDOM_ROOT_PASSWORD: yes
                    MYSQL_DATABASE: mei_test
                    MYSQL_USER: drone
                    MYSQL_PASSWORD: w33lkn0wn
                    MYSQL_INITDB_SKIP_TZINFO: yes
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Prepare environment
                id: ext-cache
                uses: shivammathur/cache-extensions@4595bea7d6630821b0a3a4894f816402faaf324c # v1
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    key: cache-v1
            -   name: Cache extensions
                uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
                with:
                    path: ${{ steps.ext-cache.outputs.dir }}
                    key: ${{ steps.ext-cache.outputs.key }}
                    restore-keys: ${{ steps.ext-cache.outputs.key }}
            -   name: Set up PHP
                uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    tools: composer
                    coverage: none
                env:
                    fail-fast: true
            -   name: Get composer cache directory
                id: deps-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   name: Cache dependencies
                uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
                with:
                    path: ${{ steps.deps-cache.outputs.dir }}
                    key: ${{ runner.os }}-${{ runner.arch }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-${{ runner.arch }}-composer-
            -   name: Install dependencies
                run: composer install --no-progress --ansi --no-dev --prefer-dist
            -   name: Prepare database schema
                run: |
                    echo -e 'mode = staging\n\n[db]\nusername = drone\npassword = w33lkn0wn\ndatabase = mei_test\nhostname = mariadb\nport = 3306' > config/private.ini
                    composer phinx seed:run -- -e staging
                    composer phinx migrate -- -e staging